### PR TITLE
CommonUtil format method remake and new unit tests

### PR DESCRIPTION
**Pull request by tomas-sexenian**
issue 97362

### CODE REVIEW

**Review by iroqueta — DISMISSED** [review]
It would be nice if you remove or change this comment (Si el value termina con un %, lo ignoro) since now isn't true anymore.
Add a unit test that test the case you have fix with this change and any other cases that you think important.

**Comment by ggallotti** [comment]
Would also be nice to improve the PR title in order to be able to understand what's the PR about without the need to go into the Issue#. 
Thanks!

**Comment by tomas-sexenian** [comment]
Updated PR title to better represent its purpose. 

When testing several different inputs to the old implementation of the format method, it failed to produce the right output in a lot of them so it seemed more appropriate  to redo the method from scratch rather than patching the old one to satisfy those said cases

**Review by tomas-sexenian — COMMENTED** [review]
Suggested changes no longer apply since the method has been reworked

**Pull request closed without merging**
